### ISSUE TITLE
Icarus tracker run error following SmartHome Demo guide

### ISSUE THREAD

**Issue by haoxli** [01org/SmartHome-Demo#19]
Following the README guide to setup SmartHome Demo in [Ostro](https://download.ostroproject.org/builds/ostro-os/2016-06-16_08-11-07-build-464/images/intel-corei7-64/ostro-image-swupd-dev-intel-corei7-64.dsk.zip),  and resolve the Python dependencies using rhe workaround in https://github.com/01org/SmartHome-Demo/issues/18, then start the Home GW SW:
```
    node first_server.js
    python icarus/python/icarus_tracker.py --location Dublin
```
Error occurs by icarus tracker:
```
root@intel-corei7-64:~/py_modules# python icarus/python/icarus_tracker.py --location Dublin 
Warning: couldn't find user config: config.json.  Using default.
using config resource: /home/root/py_modules/icarus/python/icarus/config.json
('using location: ', 'Dublin')
Traceback (most recent call last):
  File "icarus/python/icarus_tracker.py", line 42, in <module>
    go = Run(configFile.serverAddress, configFile.serverPort, configFile)
  File "/home/root/py_modules/icarus/python/icarus/actuator_pwm.py", line 16, in __init__
    self.client = s.WSClient(client_ip, client_port)
  File "/home/root/py_modules/icarus/python/icarus/solarserver.py", line 18, in __init__
    WebSocketClientFactory.__init__(self, "ws://{0}:{1}".format(address, port), debug=self.debug, origin='null', protocols=["echo-protocol"])
  File "/usr/lib/python2.7/site-packages/autobahn/twisted/websocket.py", line 278, in __init__
    protocol.WebSocketClientFactory.__init__(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'debug'
```
I doubt that whether it is because my device(NUC) has no related sensor for solar panel?

And I saw that it need special devices support in old version: https://github.com/otcshare/dollhouse/wiki/DollHouse, does the new one also need the same requirement?  The REAMDE has no clarification for  this part.

**Comment by gvancuts** [comment]
At first glance this looks a bit like a possible problem with the server address/port used. Can you check the status of your network configuration (and also whether the server address/port is reachable)?

**Comment by nagineni** [comment]
Looks to me that icarus module is broken with the new version of dependency module `autobahn` due to the WebSocket API change in it. As a workaround, you can use the old version of `autobahn <= 0.10.9` or try removing argument `debug` at https://github.com/tripzero/icarus/blob/master/python/icarus/solarserver.py#L18

**Comment by haoxli** [comment]
@nagineni  Thank you, it work with `autobahn == 0.10.9 `, the version I used is `0.14.0`, it's too high.
